export const GenericErrors = {
  NETWORK_ERROR: "NETWORK_ERROR",
  UNKNOWN_ERROR: "UNKNOWN_ERROR",
  SERVER_ERROR: "SERVER_ERROR",
  NOT_FOUND: "NOT_FOUND",
  BAD_REQUEST: "BAD_REQUEST",
  REQUEST_FAILED: "REQUEST_FAILED",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",
  CONFLICT: "CONFLICT",
  EMAIL_NOT_VERIFIED: "EMAIL_NOT_VERIFIED",
  TIMEOUT: "TIMEOUT",
  NO_DATA_FOUND: "NO_DATA_FOUND",
  UPLOAD_FAILED_NO_PATH: "UPLOAD_FAILED_NO_PATH",
  VALIDATION_ERROR: "VALIDATION_ERROR",
} as const;

export type GenericErrorsKeys = keyof typeof GenericErrors;
